spring:
  application:
    name: hr-system
  datasource:
    url: jdbc:h2:mem:hr-system
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
